version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres_volume:/var/lib/postgresql
    environment:
      - POSTGRES_DB=shorten
      - POSTGRES_USER=shorten
      - POSTGRES_PASSWORD=shorten
    networks:
      - my-network

  backend:
    build: .
    container_name: backend
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    name: my-network

volumes:
  media_volume:
  static_volume:
  postgres_volume:
