# Generated by Django 4.0.6 on 2022-08-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_url', models.TextField()),
                ('short_url', models.CharField(max_length=300)),
            ],
        ),
    ]
