# Generated by Django 4.0.6 on 2022-08-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0004_alter_shorturl_complete_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.URLField(db_index=True, unique=True),
        ),
    ]
